[2025-07-04T20:44:56.034Z] info: kubernetes.yaml was copied to the config folder
[2025-07-04T20:45:54.135Z] info: widgets.yaml was copied to the config folder
[2025-07-04T20:45:54.145Z] info: docker.yaml was copied to the config folder
[2025-07-04T20:45:54.153Z] info: services.yaml was copied to the config folder
[2025-07-04T20:45:54.154Z] info: bookmarks.yaml was copied to the config folder
[2025-07-04T20:45:54.155Z] info: custom.css was copied to the config folder
[2025-07-04T20:45:54.155Z] info: custom.js was copied to the config folder
[2025-07-04T21:09:20.074Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-04T21:09:37.421Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-04T21:09:38.345Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-04T21:09:49.330Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-04T22:09:09.101Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T01:01:04.658Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T01:04:35.637Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:15:01.815Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:15:02.112Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:16:43.015Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:18:31.074Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:19:27.327Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:21:54.001Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:28:18.102Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:28:18.374Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:28:47.203Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:29:13.920Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:29:30.071Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:29:49.510Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:34:41.209Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:34:41.795Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:35:14.570Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:35:41.150Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:35:41.614Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:35:43.683Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:35:59.795Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:36:26.657Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:36:47.315Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:39:37.815Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:39:38.073Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:39:41.055Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:39:43.591Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:39:46.498Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:40:19.206Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:40:19.429Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:40:21.014Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:40:32.962Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:40:33.199Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:40:34.528Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:40:36.855Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:41:06.906Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:41:09.008Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:41:10.371Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:41:11.369Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:41:42.124Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:41:42.399Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:41:43.401Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:41:54.347Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:41:54.594Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:41:56.347Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:41:58.353Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:41:59.458Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:42:15.432Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:42:15.687Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:42:42.152Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:42:56.656Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:43:08.701Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:43:09.076Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:43:20.879Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:43:26.822Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:44:49.213Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:44:49.484Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:44:51.123Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:45:11.006Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:45:11.369Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:45:12.099Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:45:23.475Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:45:46.118Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:45:48.146Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:45:51.928Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:46:08.645Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:46:08.841Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T02:46:44.335Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T12:25:56.464Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T12:26:31.946Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T12:26:32.203Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T12:34:53.386Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T12:34:58.389Z] error: <service-helpers> Error getting services from Docker server 'my-docker': [Error: getaddrinfo EAI_AGAIN dockerproxy] {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'dockerproxy'
}
[2025-07-05T12:34:58.624Z] error: <service-helpers> Error getting services from Docker server 'my-docker': [Error: getaddrinfo EAI_AGAIN dockerproxy] {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'dockerproxy'
}
[2025-07-05T12:34:59.801Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T12:35:03.401Z] error: <service-helpers> Error getting services from Docker server 'my-docker': [Error: getaddrinfo EAI_AGAIN dockerproxy] {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'dockerproxy'
}
[2025-07-05T12:35:03.631Z] error: <service-helpers> Error getting services from Docker server 'my-docker': [Error: getaddrinfo EAI_AGAIN dockerproxy] {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'dockerproxy'
}
[2025-07-05T12:35:08.404Z] error: <service-helpers> Error getting services from Docker server 'my-docker': [Error: getaddrinfo EAI_AGAIN dockerproxy] {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'dockerproxy'
}
[2025-07-05T13:35:13.638Z] error: <service-helpers> Error getting services from Docker server 'my-docker': [Error: getaddrinfo EAI_AGAIN dockerproxy] {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'dockerproxy'
}
[2025-07-05T13:35:15.408Z] error: <service-helpers> Error getting services from Docker server 'my-docker': [Error: getaddrinfo EAI_AGAIN dockerproxy] {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'dockerproxy'
}
[2025-07-05T13:35:22.336Z] error: <service-helpers> Error getting services from Docker server 'my-docker': [Error: getaddrinfo EAI_AGAIN dockerproxy] {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'dockerproxy'
}
[2025-07-05T13:38:20.411Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T13:38:20.459Z] error: <service-helpers> Error getting services from Docker server 'my-docker': Error: connect ECONNREFUSED 127.0.0.1:2375
    at <unknown> (Error: connect ECONNREFUSED 127.0.0.1:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 2375
}
[2025-07-05T13:38:20.714Z] error: <service-helpers> Error getting services from Docker server 'my-docker': Error: connect ECONNREFUSED 127.0.0.1:2375
    at <unknown> (Error: connect ECONNREFUSED 127.0.0.1:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 2375
}
[2025-07-05T13:38:21.057Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T13:38:21.073Z] error: <service-helpers> Error getting services from Docker server 'my-docker': Error: connect ECONNREFUSED 127.0.0.1:2375
    at <unknown> (Error: connect ECONNREFUSED 127.0.0.1:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 2375
}
[2025-07-05T13:38:37.098Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T13:38:37.105Z] error: <service-helpers> Error getting services from Docker server 'my-docker': Error: connect ECONNREFUSED 127.0.0.1:2375
    at <unknown> (Error: connect ECONNREFUSED 127.0.0.1:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 2375
}
[2025-07-05T18:37:28.406Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T18:37:29.282Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T18:42:39.806Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T18:42:40.478Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T18:42:42.275Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T18:56:00.245Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T18:59:55.130Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T18:59:55.755Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T18:59:58.980Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T19:01:27.021Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T19:01:27.550Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T19:01:28.891Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T19:03:59.448Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T19:04:00.101Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T19:04:01.462Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T19:04:03.561Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T19:04:53.574Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T19:04:53.994Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T19:04:56.080Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T19:10:08.766Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T19:10:09.380Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T19:10:21.103Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T19:12:07.511Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-05T19:16:18.477Z] error: <dockerStatusService> TypeError: Cannot read properties of null (reading 'conn')
    at l (/app/.next/server/pages/api/docker/status/[...service].js:1:1051)
    at X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18447)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
    at async handleRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:428:24)
    at async requestHandlerImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:452:13)
[2025-07-05T21:20:02.479Z] error: <httpProxy> Error calling https://adguard.snow-lab.duckdns.org/control/stats...
[2025-07-05T21:20:02.487Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN adguard.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'adguard.snow-lab.duckdns.org'
  }
]
[2025-07-05T21:20:02.704Z] error: <httpProxy> Error calling https://adguard.snow-lab.duckdns.org/control/stats...
[2025-07-05T21:20:02.705Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN adguard.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'adguard.snow-lab.duckdns.org'
  }
]
[2025-07-05T23:21:14.232Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://proxmox.snow-lab.duckdns.org/api2/json/cluster/resources
[2025-07-05T23:21:27.317Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://proxmox.snow-lab.duckdns.org/api2/json/cluster/resources
[2025-07-05T23:22:37.908Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://proxmox.snow-lab.duckdns.org/api2/json/cluster/resources
[2025-07-05T23:22:44.530Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://proxmox.snow-lab.duckdns.org/api2/json/cluster/resources
[2025-07-05T23:22:45.329Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://proxmox.snow-lab.duckdns.org/api2/json/cluster/resources
[2025-07-05T23:22:49.389Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://proxmox.snow-lab.duckdns.org/api2/json/cluster/resources
[2025-07-05T23:23:16.683Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://proxmox.snow-lab.duckdns.org/api2/json/cluster/resources
[2025-07-05T23:25:21.310Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://proxmox.snow-lab.duckdns.org/api2/json/cluster/resources
[2025-07-05T23:25:21.514Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://proxmox.snow-lab.duckdns.org/api2/json/cluster/resources
[2025-07-06T00:41:15.669Z] error: <credentialedProxyHandler> HTTP Error 403 calling https://portainer.snow-lab.duckdns.org/api/endpoints/2/docker/containers/json?all=1
[2025-07-06T00:42:52.432Z] error: <credentialedProxyHandler> HTTP Error 403 calling https://portainer.snow-lab.duckdns.org/api/endpoints/2/docker/containers/json?all=1
[2025-07-06T00:43:34.940Z] error: <credentialedProxyHandler> HTTP Error 403 calling https://portainer.snow-lab.duckdns.org/api/endpoints/2/docker/containers/json?all=1
[2025-07-06T00:43:36.305Z] error: <credentialedProxyHandler> HTTP Error 403 calling https://portainer.snow-lab.duckdns.org/api/endpoints/2/docker/containers/json?all=1
[2025-07-06T00:43:37.949Z] error: <credentialedProxyHandler> HTTP Error 403 calling https://portainer.snow-lab.duckdns.org/api/endpoints/2/docker/containers/json?all=1
[2025-07-06T00:49:12.809Z] error: <credentialedProxyHandler> HTTP Error 404 calling https://portainer.snow-lab.duckdns.org/api/endpoints/1/docker/containers/json?all=1
[2025-07-06T00:49:13.318Z] error: <credentialedProxyHandler> HTTP Error 404 calling https://portainer.snow-lab.duckdns.org/api/endpoints/1/docker/containers/json?all=1
[2025-07-06T01:00:37.926Z] error: <dockerStatusService> Error: getaddrinfo EAI_AGAIN dockerproxy
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:122:26)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-06T01:00:37.937Z] error: <dockerStatusService> Error: getaddrinfo EAI_AGAIN dockerproxy
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:122:26)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-06T01:08:06.683Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://nextcloud.snow-lab.duckdns.org/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
[2025-07-06T01:08:28.492Z] error: <dockerStatusService> Error: getaddrinfo EAI_AGAIN dockerproxy
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:122:26)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-06T01:08:28.501Z] error: <dockerStatusService> Error: getaddrinfo EAI_AGAIN dockerproxy
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:122:26)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-06T01:30:30.370Z] error: <httpProxy> Error calling https://jellyfin.snow-lab.duckdns.org/emby/Sessions...
[2025-07-06T01:30:30.376Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN jellyfin.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'jellyfin.snow-lab.duckdns.org'
  }
]
[2025-07-06T01:30:31.213Z] error: <httpProxy> Error calling https://jellyfin.snow-lab.duckdns.org/emby/Items/Counts...
[2025-07-06T01:30:31.214Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN jellyfin.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'jellyfin.snow-lab.duckdns.org'
  }
]
[2025-07-06T01:34:10.777Z] error: <httpProxy> Error calling https://portainer.snow-lab.duckdns.org/api/endpoints/2/docker/containers/json...
[2025-07-06T01:34:10.785Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN portainer.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'portainer.snow-lab.duckdns.org'
  }
]
[2025-07-06T01:34:10.786Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://portainer.snow-lab.duckdns.org/api/endpoints/2/docker/containers/json?all=1
[2025-07-06T01:34:10.789Z] error: <httpProxy> Error calling https://adguard.snow-lab.duckdns.org/control/stats...
[2025-07-06T01:34:10.790Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN adguard.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'adguard.snow-lab.duckdns.org'
  }
]
[2025-07-06T01:47:35.833Z] error: <dockerStatusService> Error: getaddrinfo EAI_AGAIN dockerproxy
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:122:26)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-06T01:47:35.853Z] error: <dockerStatusService> Error: getaddrinfo EAI_AGAIN dockerproxy
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:122:26)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-07-06T18:17:40.713Z] error: <unifiProxyHandler> HTTP 404 getting data from Unifi endpoint https://192.168.1.1/proxy/network/integrations/v1/sites/proxy/network/api/stat/sites. Data: {"statusCode":404,"statusName":"NOT_FOUND","message":"No endpoint GET /integration/v1/sites/proxy/network/api/stat/sites.","timestamp":"2025-07-06T18:17:40.693773230Z","requestPath":"/integration/v1/sites/proxy/network/api/stat/sites"}
[2025-07-06T18:17:40.715Z] error: <unifiProxyHandler> HTTP 404 getting data from Unifi endpoint https://192.168.1.1/proxy/network/integrations/v1/sites/proxy/network/api/stat/sites. Data: {"statusCode":404,"statusName":"NOT_FOUND","message":"No endpoint GET /integration/v1/sites/proxy/network/api/stat/sites.","timestamp":"2025-07-06T18:17:40.693773189Z","requestPath":"/integration/v1/sites/proxy/network/api/stat/sites"}
[2025-07-06T18:17:42.714Z] error: <unifiProxyHandler> HTTP 404 getting data from Unifi endpoint https://192.168.1.1/proxy/network/integrations/v1/sites/proxy/network/api/stat/sites. Data: {"statusCode":404,"statusName":"NOT_FOUND","message":"No endpoint GET /integration/v1/sites/proxy/network/api/stat/sites.","timestamp":"2025-07-06T18:17:42.703251769Z","requestPath":"/integration/v1/sites/proxy/network/api/stat/sites"}
[2025-07-06T18:21:00.048Z] error: <unifiProxyHandler> HTTP 404 getting data from Unifi endpoint https://192.168.1.1/proxy/network/integrations/v1/sites/proxy/network/api/stat/sites. Data: {"statusCode":404,"statusName":"NOT_FOUND","message":"No endpoint GET /integration/v1/sites/proxy/network/api/stat/sites.","timestamp":"2025-07-06T18:21:00.041492934Z","requestPath":"/integration/v1/sites/proxy/network/api/stat/sites"}
[2025-07-06T18:21:36.361Z] error: <unifiProxyHandler> HTTP 404 getting data from Unifi endpoint https://192.168.1.1/proxy/network/integrations/v1/sites/proxy/network/api/stat/sites. Data: {"statusCode":404,"statusName":"NOT_FOUND","message":"No endpoint GET /integration/v1/sites/proxy/network/api/stat/sites.","timestamp":"2025-07-06T18:21:36.352701313Z","requestPath":"/integration/v1/sites/proxy/network/api/stat/sites"}
[2025-07-06T18:21:36.599Z] error: <unifiProxyHandler> HTTP 404 getting data from Unifi endpoint https://192.168.1.1/proxy/network/integrations/v1/sites/proxy/network/api/stat/sites. Data: {"statusCode":404,"statusName":"NOT_FOUND","message":"No endpoint GET /integration/v1/sites/proxy/network/api/stat/sites.","timestamp":"2025-07-06T18:21:36.572379758Z","requestPath":"/integration/v1/sites/proxy/network/api/stat/sites"}
[2025-07-06T18:21:38.189Z] error: <unifiProxyHandler> HTTP 404 getting data from Unifi endpoint https://192.168.1.1/proxy/network/integrations/v1/sites/proxy/network/api/stat/sites. Data: {"statusCode":404,"statusName":"NOT_FOUND","message":"No endpoint GET /integration/v1/sites/proxy/network/api/stat/sites.","timestamp":"2025-07-06T18:21:38.161215105Z","requestPath":"/integration/v1/sites/proxy/network/api/stat/sites"}
[2025-07-06T18:22:04.932Z] error: <unifiProxyHandler> HTTP 404 getting data from Unifi endpoint https://192.168.1.1/proxy/network/integrations/v1/sites/proxy/network/api/stat/sites. Data: {"statusCode":404,"statusName":"NOT_FOUND","message":"No endpoint GET /integration/v1/sites/proxy/network/api/stat/sites.","timestamp":"2025-07-06T18:22:04.923424117Z","requestPath":"/integration/v1/sites/proxy/network/api/stat/sites"}
[2025-07-06T18:22:33.626Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T18:22:33.818Z] error: <unifiProxyHandler> HTTP 404 getting data from Unifi endpoint https://192.168.1.1/proxy/network/integrations/v1/sites/proxy/network/api/stat/sites. Data: {"statusCode":404,"statusName":"NOT_FOUND","message":"No endpoint GET /integration/v1/sites/proxy/network/api/stat/sites.","timestamp":"2025-07-06T18:22:33.809992448Z","requestPath":"/integration/v1/sites/proxy/network/api/stat/sites"}
[2025-07-06T18:22:34.133Z] error: <unifiProxyHandler> HTTP 404 getting data from Unifi endpoint https://192.168.1.1/proxy/network/integrations/v1/sites/proxy/network/api/stat/sites. Data: {"statusCode":404,"statusName":"NOT_FOUND","message":"No endpoint GET /integration/v1/sites/proxy/network/api/stat/sites.","timestamp":"2025-07-06T18:22:34.112161283Z","requestPath":"/integration/v1/sites/proxy/network/api/stat/sites"}
[2025-07-06T18:22:34.166Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T18:22:35.426Z] error: <unifiProxyHandler> HTTP 404 getting data from Unifi endpoint https://192.168.1.1/proxy/network/integrations/v1/sites/proxy/network/api/stat/sites. Data: {"statusCode":404,"statusName":"NOT_FOUND","message":"No endpoint GET /integration/v1/sites/proxy/network/api/stat/sites.","timestamp":"2025-07-06T18:22:35.411538593Z","requestPath":"/integration/v1/sites/proxy/network/api/stat/sites"}
[2025-07-06T18:22:35.446Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T18:22:44.736Z] error: <unifiProxyHandler> HTTP 404 getting data from Unifi endpoint https://192.168.1.1/proxy/network/integrations/v1/sites/proxy/network/api/stat/sites. Data: {"statusCode":404,"statusName":"NOT_FOUND","message":"No endpoint GET /integration/v1/sites/proxy/network/api/stat/sites.","timestamp":"2025-07-06T18:22:44.724038576Z","requestPath":"/integration/v1/sites/proxy/network/api/stat/sites"}
[2025-07-06T18:22:44.777Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T18:26:00.213Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T18:26:00.241Z] error: <unifiProxyHandler> HTTP 404 getting data from Unifi endpoint https://192.168.1.1/proxy/network/integrations/v1/sites/proxy/network/api/stat/sites. Data: {"statusCode":404,"statusName":"NOT_FOUND","message":"No endpoint GET /integration/v1/sites/proxy/network/api/stat/sites.","timestamp":"2025-07-06T18:26:00.233754786Z","requestPath":"/integration/v1/sites/proxy/network/api/stat/sites"}
[2025-07-06T18:26:00.557Z] error: <unifiProxyHandler> HTTP 404 getting data from Unifi endpoint https://192.168.1.1/proxy/network/integrations/v1/sites/proxy/network/api/stat/sites. Data: {"statusCode":404,"statusName":"NOT_FOUND","message":"No endpoint GET /integration/v1/sites/proxy/network/api/stat/sites.","timestamp":"2025-07-06T18:26:00.548909362Z","requestPath":"/integration/v1/sites/proxy/network/api/stat/sites"}
[2025-07-06T18:26:00.589Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T18:26:54.209Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T18:26:54.584Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T18:26:54.605Z] error: <unifiProxyHandler> HTTP 404 getting data from Unifi endpoint https://192.168.1.1/proxy/network/integrations/v1/sites/proxy/network/api/stat/sites. Data: {"statusCode":404,"statusName":"NOT_FOUND","message":"No endpoint GET /integration/v1/sites/proxy/network/api/stat/sites.","timestamp":"2025-07-06T18:26:54.598203793Z","requestPath":"/integration/v1/sites/proxy/network/api/stat/sites"}
[2025-07-06T18:26:57.470Z] error: <unifiProxyHandler> HTTP 404 getting data from Unifi endpoint https://192.168.1.1/proxy/network/integrations/v1/sites/proxy/network/api/stat/sites. Data: {"statusCode":404,"statusName":"NOT_FOUND","message":"No endpoint GET /integration/v1/sites/proxy/network/api/stat/sites.","timestamp":"2025-07-06T18:26:57.454937306Z","requestPath":"/integration/v1/sites/proxy/network/api/stat/sites"}
[2025-07-06T18:26:57.472Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T18:27:54.956Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T18:27:54.994Z] error: <unifiProxyHandler> HTTP 404 getting data from Unifi endpoint https://192.168.1.1/proxy/network/integrations/v1/sites/proxy/network/api/stat/sites. Data: {"statusCode":404,"statusName":"NOT_FOUND","message":"No endpoint GET /integration/v1/sites/proxy/network/api/stat/sites.","timestamp":"2025-07-06T18:27:54.987312371Z","requestPath":"/integration/v1/sites/proxy/network/api/stat/sites"}
[2025-07-06T18:27:55.284Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T18:27:55.305Z] error: <unifiProxyHandler> HTTP 404 getting data from Unifi endpoint https://192.168.1.1/proxy/network/integrations/v1/sites/proxy/network/api/stat/sites. Data: {"statusCode":404,"statusName":"NOT_FOUND","message":"No endpoint GET /integration/v1/sites/proxy/network/api/stat/sites.","timestamp":"2025-07-06T18:27:55.287976431Z","requestPath":"/integration/v1/sites/proxy/network/api/stat/sites"}
[2025-07-06T18:27:55.733Z] error: <unifiProxyHandler> HTTP 404 getting data from Unifi endpoint https://192.168.1.1/proxy/network/integrations/v1/sites/proxy/network/api/stat/sites. Data: {"statusCode":404,"statusName":"NOT_FOUND","message":"No endpoint GET /integration/v1/sites/proxy/network/api/stat/sites.","timestamp":"2025-07-06T18:27:55.719516842Z","requestPath":"/integration/v1/sites/proxy/network/api/stat/sites"}
[2025-07-06T18:27:55.758Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T18:38:58.665Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T18:38:58.669Z] error: <unifiProxyHandler> HTTP 404 getting data from Unifi endpoint https://192.168.1.1/proxy/network/integrations/v1/sites/proxy/network/api/stat/sites. Data: {"statusCode":404,"statusName":"NOT_FOUND","message":"No endpoint GET /integration/v1/sites/proxy/network/api/stat/sites.","timestamp":"2025-07-06T18:38:58.661178880Z","requestPath":"/integration/v1/sites/proxy/network/api/stat/sites"}
[2025-07-06T18:38:58.957Z] error: <unifiProxyHandler> HTTP 404 getting data from Unifi endpoint https://192.168.1.1/proxy/network/integrations/v1/sites/proxy/network/api/stat/sites. Data: {"statusCode":404,"statusName":"NOT_FOUND","message":"No endpoint GET /integration/v1/sites/proxy/network/api/stat/sites.","timestamp":"2025-07-06T18:38:58.951352089Z","requestPath":"/integration/v1/sites/proxy/network/api/stat/sites"}
[2025-07-06T18:38:58.961Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T18:39:05.143Z] error: <httpProxy> Error calling https://kuma.snow-lab.duckdns.org/api/status-page/heartbeat/homepage...
[2025-07-06T18:39:05.148Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN kuma.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'kuma.snow-lab.duckdns.org'
  }
]
[2025-07-06T18:40:19.630Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T18:40:19.662Z] error: <unifiProxyHandler> HTTP 404 getting data from Unifi endpoint https://192.168.1.1/proxy/network/integrations/v1/sites/proxy/network/api/stat/sites. Data: {"statusCode":404,"statusName":"NOT_FOUND","message":"No endpoint GET /integration/v1/sites/proxy/network/api/stat/sites.","timestamp":"2025-07-06T18:40:19.656675768Z","requestPath":"/integration/v1/sites/proxy/network/api/stat/sites"}
[2025-07-06T18:40:19.874Z] error: <unifiProxyHandler> HTTP 404 getting data from Unifi endpoint https://192.168.1.1/proxy/network/integrations/v1/sites/proxy/network/api/stat/sites. Data: {"statusCode":404,"statusName":"NOT_FOUND","message":"No endpoint GET /integration/v1/sites/proxy/network/api/stat/sites.","timestamp":"2025-07-06T18:40:19.868691752Z","requestPath":"/integration/v1/sites/proxy/network/api/stat/sites"}
[2025-07-06T18:40:19.882Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T18:40:20.688Z] error: <unifiProxyHandler> HTTP 404 getting data from Unifi endpoint https://192.168.1.1/proxy/network/integrations/v1/sites/proxy/network/api/stat/sites. Data: {"statusCode":404,"statusName":"NOT_FOUND","message":"No endpoint GET /integration/v1/sites/proxy/network/api/stat/sites.","timestamp":"2025-07-06T18:40:20.674151337Z","requestPath":"/integration/v1/sites/proxy/network/api/stat/sites"}
[2025-07-06T18:40:20.693Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T18:40:28.655Z] error: <unifiProxyHandler> HTTP 404 getting data from Unifi endpoint https://192.168.1.1/proxy/network/integrations/v1/sites/proxy/network/api/stat/sites. Data: {"statusCode":404,"statusName":"NOT_FOUND","message":"No endpoint GET /integration/v1/sites/proxy/network/api/stat/sites.","timestamp":"2025-07-06T18:40:28.636707554Z","requestPath":"/integration/v1/sites/proxy/network/api/stat/sites"}
[2025-07-06T18:40:28.699Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T18:40:43.623Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T18:40:43.630Z] error: <unifiProxyHandler> HTTP 404 getting data from Unifi endpoint https://192.168.1.1/proxy/network/integrations/v1/sites/proxy/network/api/stat/sites. Data: {"statusCode":404,"statusName":"NOT_FOUND","message":"No endpoint GET /integration/v1/sites/proxy/network/api/stat/sites.","timestamp":"2025-07-06T18:40:43.624516832Z","requestPath":"/integration/v1/sites/proxy/network/api/stat/sites"}
[2025-07-06T18:40:43.873Z] error: <unifiProxyHandler> HTTP 404 getting data from Unifi endpoint https://192.168.1.1/proxy/network/integrations/v1/sites/proxy/network/api/stat/sites. Data: {"statusCode":404,"statusName":"NOT_FOUND","message":"No endpoint GET /integration/v1/sites/proxy/network/api/stat/sites.","timestamp":"2025-07-06T18:40:43.858103800Z","requestPath":"/integration/v1/sites/proxy/network/api/stat/sites"}
[2025-07-06T18:40:43.934Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T18:43:22.906Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T18:43:22.926Z] error: <unifiProxyHandler> HTTP 404 getting data from Unifi endpoint https://192.168.1.1/proxy/network/integrations/v1/sites/proxy/network/api/stat/sites. Data: {"statusCode":404,"statusName":"NOT_FOUND","message":"No endpoint GET /integration/v1/sites/proxy/network/api/stat/sites.","timestamp":"2025-07-06T18:43:22.920151099Z","requestPath":"/integration/v1/sites/proxy/network/api/stat/sites"}
[2025-07-06T18:43:23.128Z] error: <unifiProxyHandler> HTTP 404 getting data from Unifi endpoint https://192.168.1.1/proxy/network/integrations/v1/sites/proxy/network/api/stat/sites. Data: {"statusCode":404,"statusName":"NOT_FOUND","message":"No endpoint GET /integration/v1/sites/proxy/network/api/stat/sites.","timestamp":"2025-07-06T18:43:23.122550573Z","requestPath":"/integration/v1/sites/proxy/network/api/stat/sites"}
[2025-07-06T18:43:23.130Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T18:49:57.349Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T18:49:57.381Z] error: <unifiProxyHandler> HTTP 404 getting data from Unifi endpoint https://192.168.1.1/proxy/network/integrations/v1/sites/proxy/network/api/stat/sites. Data: {"statusCode":404,"statusName":"NOT_FOUND","message":"No endpoint GET /integration/v1/sites/proxy/network/api/stat/sites.","timestamp":"2025-07-06T18:49:57.375106527Z","requestPath":"/integration/v1/sites/proxy/network/api/stat/sites"}
[2025-07-06T18:50:44.521Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T18:50:44.594Z] error: <unifiProxyHandler> HTTP 404 getting data from Unifi endpoint https://192.168.1.1/proxy/network/integrations/v1/sites/proxy/network/api/stat/sites. Data: {"statusCode":404,"statusName":"NOT_FOUND","message":"No endpoint GET /integration/v1/sites/proxy/network/api/stat/sites.","timestamp":"2025-07-06T18:50:44.577646471Z","requestPath":"/integration/v1/sites/proxy/network/api/stat/sites"}
[2025-07-06T18:50:44.890Z] error: <unifiProxyHandler> HTTP 404 getting data from Unifi endpoint https://192.168.1.1/proxy/network/integrations/v1/sites/proxy/network/api/stat/sites. Data: {"statusCode":404,"statusName":"NOT_FOUND","message":"No endpoint GET /integration/v1/sites/proxy/network/api/stat/sites.","timestamp":"2025-07-06T18:50:44.877340292Z","requestPath":"/integration/v1/sites/proxy/network/api/stat/sites"}
[2025-07-06T18:50:44.950Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T18:51:35.852Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T18:51:35.893Z] error: <unifiProxyHandler> HTTP 404 getting data from Unifi endpoint https://192.168.1.1/proxy/network/integrations/v1/sites/proxy/network/api/stat/sites. Data: {"statusCode":404,"statusName":"NOT_FOUND","message":"No endpoint GET /integration/v1/sites/proxy/network/api/stat/sites.","timestamp":"2025-07-06T18:51:35.887950701Z","requestPath":"/integration/v1/sites/proxy/network/api/stat/sites"}
[2025-07-06T18:51:36.156Z] error: <unifiProxyHandler> HTTP 404 getting data from Unifi endpoint https://192.168.1.1/proxy/network/integrations/v1/sites/proxy/network/api/stat/sites. Data: {"statusCode":404,"statusName":"NOT_FOUND","message":"No endpoint GET /integration/v1/sites/proxy/network/api/stat/sites.","timestamp":"2025-07-06T18:51:36.145570397Z","requestPath":"/integration/v1/sites/proxy/network/api/stat/sites"}
[2025-07-06T18:51:36.227Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T18:52:08.582Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T18:52:08.617Z] error: <unifiProxyHandler> HTTP 404 getting data from Unifi endpoint https://192.168.1.1/proxy/network/integrations/v1/sites/proxy/network/api/stat/sites. Data: {"statusCode":404,"statusName":"NOT_FOUND","message":"No endpoint GET /integration/v1/sites/proxy/network/api/stat/sites.","timestamp":"2025-07-06T18:52:08.612119375Z","requestPath":"/integration/v1/sites/proxy/network/api/stat/sites"}
[2025-07-06T18:52:52.942Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T18:52:52.965Z] error: <unifiProxyHandler> HTTP 404 getting data from Unifi endpoint https://192.168.1.1/proxy/network/integrations/v1/sites/proxy/network/api/stat/sites. Data: {"statusCode":404,"statusName":"NOT_FOUND","message":"No endpoint GET /integration/v1/sites/proxy/network/api/stat/sites.","timestamp":"2025-07-06T18:52:52.960616234Z","requestPath":"/integration/v1/sites/proxy/network/api/stat/sites"}
[2025-07-06T18:52:53.232Z] error: <unifiProxyHandler> HTTP 404 getting data from Unifi endpoint https://192.168.1.1/proxy/network/integrations/v1/sites/proxy/network/api/stat/sites. Data: {"statusCode":404,"statusName":"NOT_FOUND","message":"No endpoint GET /integration/v1/sites/proxy/network/api/stat/sites.","timestamp":"2025-07-06T18:52:53.223773736Z","requestPath":"/integration/v1/sites/proxy/network/api/stat/sites"}
[2025-07-06T18:52:53.286Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T18:53:34.531Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T18:53:34.866Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T18:56:54.068Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T18:59:16.889Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T19:00:40.299Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T19:00:59.560Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T19:08:55.099Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T19:08:55.473Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T19:09:04.557Z] error: <httpProxy> Error calling https://adguard.snow-lab.duckdns.org/control/stats...
[2025-07-06T19:09:04.562Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN adguard.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'adguard.snow-lab.duckdns.org'
  }
]
[2025-07-06T19:09:05.357Z] error: <httpProxy> Error calling https://adguard.snow-lab.duckdns.org/control/stats...
[2025-07-06T19:09:05.359Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN adguard.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'adguard.snow-lab.duckdns.org'
  }
]
[2025-07-06T19:09:19.820Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T19:09:24.838Z] error: <httpProxy> Error calling https://nextcloud.snow-lab.duckdns.org/ocs/v2.php/apps/serverinfo/api/v1/info...
[2025-07-06T19:09:24.840Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN nextcloud.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'nextcloud.snow-lab.duckdns.org'
  }
]
[2025-07-06T19:09:24.840Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://nextcloud.snow-lab.duckdns.org/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
[2025-07-06T19:09:24.841Z] error: <httpProxy> Error calling https://traefik.snow-lab.duckdns.org/api/overview...
[2025-07-06T19:09:24.842Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN traefik.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'traefik.snow-lab.duckdns.org'
  }
]
[2025-07-06T19:09:45.147Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T19:10:55.541Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T19:11:00.994Z] error: <httpProxy> Error calling https://proxmox.snow-lab.duckdns.org/api2/json/cluster/resources...
[2025-07-06T19:11:00.995Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN proxmox.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'proxmox.snow-lab.duckdns.org'
  }
]
[2025-07-06T19:11:00.996Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://proxmox.snow-lab.duckdns.org/api2/json/cluster/resources
[2025-07-06T19:12:06.593Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T19:12:07.782Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T19:12:12.878Z] error: <httpProxy> Error calling https://kuma.snow-lab.duckdns.org/api/status-page/homepage...
[2025-07-06T19:12:12.879Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN kuma.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'kuma.snow-lab.duckdns.org'
  }
]
[2025-07-06T19:13:10.540Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T19:13:42.363Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T19:13:42.682Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T19:14:41.109Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T19:14:50.218Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T19:16:57.587Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T19:16:57.879Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T19:17:23.514Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T19:17:23.877Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T19:19:02.507Z] error: <index> YAMLException: bad indentation of a mapping entry (13:15)

 10 | - Social:
 11 |     - Reddit:
 12 |       - icon: reddit.svg
 13 |           href: https://reddit.com/
--------------------^
 14 | 
 15 | - Entertainment:
    at generateError (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:1273:10)
    at throwError (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:1277:9)
    at readBlockMapping (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2272:7)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2531:12)
    at readBlockSequence (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2098:5)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2562:45)
    at readBlockMapping (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2254:11)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2531:12)
    at readBlockSequence (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2098:5)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2530:12)
[2025-07-06T19:19:02.520Z] error: bad indentation of a mapping entry (13:15)

 10 | - Social:
 11 |     - Reddit:
 12 |       - icon: reddit.svg
 13 |           href: https://reddit.com/
--------------------^
 14 | 
 15 | - Entertainment:
[2025-07-06T19:19:02.523Z] error: YAMLException: bad indentation of a mapping entry (13:15)

 10 | - Social:
 11 |     - Reddit:
 12 |       - icon: reddit.svg
 13 |           href: https://reddit.com/
--------------------^
 14 | 
 15 | - Entertainment:
    at generateError (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:1273:10)
    at throwError (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:1277:9)
    at readBlockMapping (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2272:7)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2531:12)
    at readBlockSequence (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2098:5)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2562:45)
    at readBlockMapping (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2254:11)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2531:12)
    at readBlockSequence (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2098:5)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2530:12)
[2025-07-06T19:19:02.568Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T19:19:02.694Z] error: bad indentation of a mapping entry (13:15)

 10 | - Social:
 11 |     - Reddit:
 12 |       - icon: reddit.svg
 13 |           href: https://reddit.com/
--------------------^
 14 | 
 15 | - Entertainment:
[2025-07-06T19:19:02.695Z] error: YAMLException: bad indentation of a mapping entry (13:15)

 10 | - Social:
 11 |     - Reddit:
 12 |       - icon: reddit.svg
 13 |           href: https://reddit.com/
--------------------^
 14 | 
 15 | - Entertainment:
    at generateError (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:1273:10)
    at throwError (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:1277:9)
    at readBlockMapping (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2272:7)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2531:12)
    at readBlockSequence (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2098:5)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2562:45)
    at readBlockMapping (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2254:11)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2531:12)
    at readBlockSequence (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2098:5)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2530:12)
[2025-07-06T19:19:18.305Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T19:20:58.648Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T19:21:04.660Z] error: <httpProxy> Error calling https://kuma.snow-lab.duckdns.org/api/status-page/homepage...
[2025-07-06T19:21:04.661Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN kuma.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'kuma.snow-lab.duckdns.org'
  }
]
[2025-07-06T19:21:05.724Z] error: <httpProxy> Error calling https://kuma.snow-lab.duckdns.org/api/status-page/heartbeat/homepage...
[2025-07-06T19:21:05.725Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN kuma.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'kuma.snow-lab.duckdns.org'
  }
]
[2025-07-06T19:21:10.832Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T19:21:38.765Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T19:24:37.122Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T19:24:47.136Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T19:25:41.500Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T19:49:15.098Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T19:53:32.457Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T19:53:32.796Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T19:53:48.173Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T19:53:57.016Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T19:54:19.334Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T19:54:19.470Z] error: <httpProxy> Error calling https://api.openweathermap.org/data/2.5/weather...
[2025-07-06T19:54:19.470Z] error: <httpProxy> [ 500, [AggregateError: ] { code: 'ETIMEDOUT' } ]
[2025-07-06T19:54:19.708Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T19:54:36.519Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-06T19:54:54.921Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-07T20:32:31.149Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-07T20:32:36.107Z] error: <httpProxy> Error calling https://proxmox.snow-lab.duckdns.org/api2/json/cluster/resources...
[2025-07-07T20:32:36.108Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN proxmox.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'proxmox.snow-lab.duckdns.org'
  }
]
[2025-07-07T20:32:36.108Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://proxmox.snow-lab.duckdns.org/api2/json/cluster/resources
[2025-07-07T20:32:37.103Z] error: <httpProxy> Error calling https://kuma.snow-lab.duckdns.org/api/status-page/homepage...
[2025-07-07T20:32:37.104Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN kuma.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'kuma.snow-lab.duckdns.org'
  }
]
[2025-07-07T20:32:41.060Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-07T20:32:41.109Z] error: <httpProxy> Error calling https://kuma.snow-lab.duckdns.org/api/status-page/heartbeat/homepage...
[2025-07-07T20:32:41.110Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN kuma.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'kuma.snow-lab.duckdns.org'
  }
]
[2025-07-07T20:32:42.107Z] error: <httpProxy> Error calling https://adguard.snow-lab.duckdns.org/control/stats...
[2025-07-07T20:32:42.108Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN adguard.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'adguard.snow-lab.duckdns.org'
  }
]
[2025-07-07T20:32:46.112Z] error: <httpProxy> Error calling https://jellyfin.snow-lab.duckdns.org/emby/Sessions...
[2025-07-07T20:32:46.113Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN jellyfin.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'jellyfin.snow-lab.duckdns.org'
  }
]
[2025-07-07T20:32:50.426Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-07T20:32:51.116Z] error: <httpProxy> Error calling https://traefik.snow-lab.duckdns.org/api/overview...
[2025-07-07T20:32:51.116Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN traefik.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'traefik.snow-lab.duckdns.org'
  }
]
[2025-07-07T20:33:04.714Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-07T20:33:13.820Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-07T20:33:15.550Z] error: <httpProxy> Error calling https://jellyfin.snow-lab.duckdns.org/emby/Sessions...
[2025-07-07T20:33:15.551Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN jellyfin.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'jellyfin.snow-lab.duckdns.org'
  }
]
[2025-07-07T20:33:24.924Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-07T20:33:34.950Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-07T20:33:39.944Z] error: <httpProxy> Error calling https://immich.snow-lab.duckdns.org/api/server/statistics...
[2025-07-07T20:33:39.945Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN immich.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'immich.snow-lab.duckdns.org'
  }
]
[2025-07-07T20:33:39.945Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://immich.snow-lab.duckdns.org/api/server/statistics
[2025-07-07T20:33:39.950Z] error: <httpProxy> Error calling https://portainer.snow-lab.duckdns.org/api/endpoints/2/docker/containers/json...
[2025-07-07T20:33:39.950Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN portainer.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'portainer.snow-lab.duckdns.org'
  }
]
[2025-07-07T20:33:39.951Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://portainer.snow-lab.duckdns.org/api/endpoints/2/docker/containers/json?all=1
[2025-07-07T20:33:44.947Z] error: <httpProxy> Error calling https://immich.snow-lab.duckdns.org/api/server/version...
[2025-07-07T20:33:44.947Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN immich.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'immich.snow-lab.duckdns.org'
  }
]
[2025-07-07T20:33:44.947Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://immich.snow-lab.duckdns.org/api/server/version
[2025-07-07T20:33:48.972Z] error: <httpProxy> Error calling https://kuma.snow-lab.duckdns.org/api/status-page/homepage...
[2025-07-07T20:33:48.973Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN kuma.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'kuma.snow-lab.duckdns.org'
  }
]
[2025-07-07T20:35:09.617Z] error: <httpProxy> Error calling https://traefik.snow-lab.duckdns.org/api/overview...
[2025-07-07T20:35:09.618Z] error: <httpProxy> [
  500,
  Error: connect ETIMEDOUT 192.168.1.23:443
      at <unknown> (Error: connect ETIMEDOUT 192.168.1.23:443) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '192.168.1.23',
    port: 443
  }
]
[2025-07-07T20:35:34.192Z] error: <httpProxy> Error calling https://traefik.snow-lab.duckdns.org/api/overview...
[2025-07-07T20:35:34.193Z] error: <httpProxy> [
  500,
  Error: connect ETIMEDOUT 192.168.1.23:443
      at <unknown> (Error: connect ETIMEDOUT 192.168.1.23:443) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '192.168.1.23',
    port: 443
  }
]
[2025-07-07T20:45:17.369Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-07T20:45:22.252Z] error: <httpProxy> Error calling https://traefik.snow-lab.duckdns.org/api/overview...
[2025-07-07T20:45:22.253Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN traefik.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'traefik.snow-lab.duckdns.org'
  }
]
[2025-07-07T20:45:22.255Z] error: <httpProxy> Error calling https://adguard.snow-lab.duckdns.org/control/stats...
[2025-07-07T20:45:22.255Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN adguard.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'adguard.snow-lab.duckdns.org'
  }
]
[2025-07-07T20:45:25.353Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-07T20:45:27.256Z] error: <httpProxy> Error calling https://immich.snow-lab.duckdns.org/api/server/statistics...
[2025-07-07T20:45:27.257Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN immich.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'immich.snow-lab.duckdns.org'
  }
]
[2025-07-07T20:45:27.257Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://immich.snow-lab.duckdns.org/api/server/statistics
[2025-07-07T20:45:27.258Z] error: <httpProxy> Error calling https://kuma.snow-lab.duckdns.org/api/status-page/homepage...
[2025-07-07T20:45:27.258Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN kuma.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'kuma.snow-lab.duckdns.org'
  }
]
[2025-07-07T20:45:32.261Z] error: <httpProxy> Error calling https://kuma.snow-lab.duckdns.org/api/status-page/heartbeat/homepage...
[2025-07-07T20:45:32.261Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN kuma.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'kuma.snow-lab.duckdns.org'
  }
]
[2025-07-07T20:45:32.262Z] error: <httpProxy> Error calling https://immich.snow-lab.duckdns.org/api/server/version...
[2025-07-07T20:45:32.263Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN immich.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'immich.snow-lab.duckdns.org'
  }
]
[2025-07-07T20:45:32.263Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://immich.snow-lab.duckdns.org/api/server/version
[2025-07-07T20:45:43.481Z] error: <httpProxy> Error calling https://proxmox.snow-lab.duckdns.org/api2/json/cluster/resources...
[2025-07-07T20:45:43.482Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN proxmox.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'proxmox.snow-lab.duckdns.org'
  }
]
[2025-07-07T20:45:43.482Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://proxmox.snow-lab.duckdns.org/api2/json/cluster/resources
[2025-07-07T20:45:44.958Z] error: <httpProxy> Error calling https://kuma.snow-lab.duckdns.org/api/status-page/homepage...
[2025-07-07T20:45:44.959Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN kuma.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'kuma.snow-lab.duckdns.org'
  }
]
[2025-07-07T20:45:49.961Z] error: <httpProxy> Error calling https://proxmox.snow-lab.duckdns.org/api2/json/cluster/resources...
[2025-07-07T20:45:49.962Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN proxmox.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'proxmox.snow-lab.duckdns.org'
  }
]
[2025-07-07T20:45:49.962Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://proxmox.snow-lab.duckdns.org/api2/json/cluster/resources
[2025-07-07T20:45:52.891Z] error: <httpProxy> Error calling https://kuma.snow-lab.duckdns.org/api/status-page/heartbeat/homepage...
[2025-07-07T20:45:52.891Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN kuma.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'kuma.snow-lab.duckdns.org'
  }
]
[2025-07-07T20:46:13.547Z] error: <httpProxy> Error calling https://jellyfin.snow-lab.duckdns.org/emby/Sessions...
[2025-07-07T20:46:13.548Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN jellyfin.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'jellyfin.snow-lab.duckdns.org'
  }
]
[2025-07-07T20:46:43.786Z] error: <httpProxy> Error calling https://jellyfin.snow-lab.duckdns.org/emby/Sessions...
[2025-07-07T20:46:43.787Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN jellyfin.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'jellyfin.snow-lab.duckdns.org'
  }
]
[2025-07-07T20:46:53.822Z] error: <httpProxy> Error calling https://jellyfin.snow-lab.duckdns.org/emby/Sessions...
[2025-07-07T20:46:53.823Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN jellyfin.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'jellyfin.snow-lab.duckdns.org'
  }
]
[2025-07-07T20:48:02.460Z] error: <httpProxy> Error calling https://jellyfin.snow-lab.duckdns.org/emby/Items/Counts...
[2025-07-07T20:48:02.461Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN jellyfin.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'jellyfin.snow-lab.duckdns.org'
  }
]
[2025-07-07T20:48:52.254Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-07T20:48:57.209Z] error: <httpProxy> Error calling https://portainer.snow-lab.duckdns.org/api/endpoints/2/docker/containers/json...
[2025-07-07T20:48:57.210Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN portainer.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'portainer.snow-lab.duckdns.org'
  }
]
[2025-07-07T20:48:57.210Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://portainer.snow-lab.duckdns.org/api/endpoints/2/docker/containers/json?all=1
[2025-07-07T20:48:57.214Z] error: <httpProxy> Error calling https://proxmox.snow-lab.duckdns.org/api2/json/cluster/resources...
[2025-07-07T20:48:57.215Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN proxmox.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'proxmox.snow-lab.duckdns.org'
  }
]
[2025-07-07T20:48:57.215Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://proxmox.snow-lab.duckdns.org/api2/json/cluster/resources
[2025-07-07T20:49:02.215Z] error: <httpProxy> Error calling https://adguard.snow-lab.duckdns.org/control/stats...
[2025-07-07T20:49:02.215Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN adguard.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'adguard.snow-lab.duckdns.org'
  }
]
[2025-07-07T20:49:02.341Z] error: <httpProxy> Error calling https://kuma.snow-lab.duckdns.org/api/status-page/homepage...
[2025-07-07T20:49:02.342Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN kuma.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'kuma.snow-lab.duckdns.org'
  }
]
[2025-07-07T20:49:07.219Z] error: <httpProxy> Error calling https://kuma.snow-lab.duckdns.org/api/status-page/heartbeat/homepage...
[2025-07-07T20:49:07.220Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN kuma.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'kuma.snow-lab.duckdns.org'
  }
]
[2025-07-07T20:49:07.415Z] error: <httpProxy> Error calling https://nextcloud.snow-lab.duckdns.org/ocs/v2.php/apps/serverinfo/api/v1/info...
[2025-07-07T20:49:07.416Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN nextcloud.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'nextcloud.snow-lab.duckdns.org'
  }
]
[2025-07-07T20:49:07.416Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://nextcloud.snow-lab.duckdns.org/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
[2025-07-07T20:49:12.223Z] error: <httpProxy> Error calling https://jellyfin.snow-lab.duckdns.org/emby/Sessions...
[2025-07-07T20:49:12.224Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN jellyfin.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'jellyfin.snow-lab.duckdns.org'
  }
]
[2025-07-07T20:50:17.807Z] error: <httpProxy> Error calling https://jellyfin.snow-lab.duckdns.org/emby/Sessions...
[2025-07-07T20:50:17.808Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN jellyfin.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'jellyfin.snow-lab.duckdns.org'
  }
]
[2025-07-07T20:50:27.839Z] error: <httpProxy> Error calling https://jellyfin.snow-lab.duckdns.org/emby/Sessions...
[2025-07-07T20:50:27.840Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN jellyfin.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'jellyfin.snow-lab.duckdns.org'
  }
]
[2025-07-07T20:50:37.868Z] error: <httpProxy> Error calling https://jellyfin.snow-lab.duckdns.org/emby/Sessions...
[2025-07-07T20:50:37.868Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN jellyfin.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'jellyfin.snow-lab.duckdns.org'
  }
]
[2025-07-07T20:51:12.177Z] error: <httpProxy> Error calling https://traefik.snow-lab.duckdns.org/api/overview...
[2025-07-07T20:51:12.178Z] error: <httpProxy> [
  500,
  Error: connect ETIMEDOUT 192.168.1.23:443
      at <unknown> (Error: connect ETIMEDOUT 192.168.1.23:443) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '192.168.1.23',
    port: 443
  }
]
[2025-07-07T20:51:48.488Z] error: <httpProxy> Error calling https://jellyfin.snow-lab.duckdns.org/emby/Sessions...
[2025-07-07T20:51:48.489Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN jellyfin.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'jellyfin.snow-lab.duckdns.org'
  }
]
[2025-07-07T20:52:28.909Z] error: <httpProxy> Error calling https://jellyfin.snow-lab.duckdns.org/emby/Sessions...
[2025-07-07T20:52:28.910Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN jellyfin.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'jellyfin.snow-lab.duckdns.org'
  }
]
[2025-07-07T20:53:09.278Z] error: <httpProxy> Error calling https://jellyfin.snow-lab.duckdns.org/emby/Sessions...
[2025-07-07T20:53:09.279Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN jellyfin.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'jellyfin.snow-lab.duckdns.org'
  }
]
[2025-07-07T20:55:42.114Z] error: <httpProxy> Error calling https://jellyfin.snow-lab.duckdns.org/emby/Sessions...
[2025-07-07T20:55:42.115Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN jellyfin.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'jellyfin.snow-lab.duckdns.org'
  }
]
[2025-07-07T20:55:52.150Z] error: <httpProxy> Error calling https://jellyfin.snow-lab.duckdns.org/emby/Sessions...
[2025-07-07T20:55:52.151Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN jellyfin.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'jellyfin.snow-lab.duckdns.org'
  }
]
[2025-07-07T20:56:02.187Z] error: <httpProxy> Error calling https://jellyfin.snow-lab.duckdns.org/emby/Sessions...
[2025-07-07T20:56:02.187Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN jellyfin.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'jellyfin.snow-lab.duckdns.org'
  }
]
[2025-07-07T21:00:07.076Z] error: <httpProxy> Error calling https://jellyfin.snow-lab.duckdns.org/emby/Sessions...
[2025-07-07T21:00:07.077Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN jellyfin.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'jellyfin.snow-lab.duckdns.org'
  }
]
[2025-07-07T21:00:08.019Z] error: <httpProxy> Error calling https://jellyfin.snow-lab.duckdns.org/emby/Items/Counts...
[2025-07-07T21:00:08.020Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN jellyfin.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'jellyfin.snow-lab.duckdns.org'
  }
]
[2025-07-07T21:01:17.753Z] error: <httpProxy> Error calling https://jellyfin.snow-lab.duckdns.org/emby/Sessions...
[2025-07-07T21:01:17.754Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN jellyfin.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'jellyfin.snow-lab.duckdns.org'
  }
]
[2025-07-07T21:01:27.783Z] error: <httpProxy> Error calling https://jellyfin.snow-lab.duckdns.org/emby/Sessions...
[2025-07-07T21:01:27.784Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN jellyfin.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'jellyfin.snow-lab.duckdns.org'
  }
]
[2025-07-07T21:03:35.120Z] error: <httpProxy> Error calling https://jellyfin.snow-lab.duckdns.org/emby/Sessions...
[2025-07-07T21:03:35.121Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN jellyfin.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'jellyfin.snow-lab.duckdns.org'
  }
]
[2025-07-07T21:05:50.390Z] error: <httpProxy> Error calling https://jellyfin.snow-lab.duckdns.org/emby/Sessions...
[2025-07-07T21:05:50.391Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN jellyfin.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'jellyfin.snow-lab.duckdns.org'
  }
]
[2025-07-07T21:06:10.534Z] error: <httpProxy> Error calling https://jellyfin.snow-lab.duckdns.org/emby/Sessions...
[2025-07-07T21:06:10.534Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN jellyfin.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'jellyfin.snow-lab.duckdns.org'
  }
]
[2025-07-07T21:06:13.289Z] error: <httpProxy> Error calling https://jellyfin.snow-lab.duckdns.org/emby/Items/Counts...
[2025-07-07T21:06:13.289Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN jellyfin.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'jellyfin.snow-lab.duckdns.org'
  }
]
[2025-07-07T21:06:20.563Z] error: <httpProxy> Error calling https://jellyfin.snow-lab.duckdns.org/emby/Sessions...
[2025-07-07T21:06:20.564Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN jellyfin.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'jellyfin.snow-lab.duckdns.org'
  }
]
[2025-07-07T21:07:32.381Z] error: <httpProxy> Error calling https://jellyfin.snow-lab.duckdns.org/emby/Sessions...
[2025-07-07T21:07:32.381Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN jellyfin.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'jellyfin.snow-lab.duckdns.org'
  }
]
[2025-07-07T21:08:49.189Z] error: <httpProxy> Error calling https://jellyfin.snow-lab.duckdns.org/emby/Sessions...
[2025-07-07T21:08:49.190Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN jellyfin.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'jellyfin.snow-lab.duckdns.org'
  }
]
[2025-07-07T21:09:29.530Z] error: <httpProxy> Error calling https://jellyfin.snow-lab.duckdns.org/emby/Sessions...
[2025-07-07T21:09:29.531Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN jellyfin.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'jellyfin.snow-lab.duckdns.org'
  }
]
[2025-07-07T21:11:15.282Z] error: <httpProxy> Error calling https://jellyfin.snow-lab.duckdns.org/emby/Sessions...
[2025-07-07T21:11:15.283Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN jellyfin.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'jellyfin.snow-lab.duckdns.org'
  }
]
[2025-07-07T21:12:21.977Z] error: <httpProxy> Error calling https://jellyfin.snow-lab.duckdns.org/emby/Items/Counts...
[2025-07-07T21:12:21.978Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN jellyfin.snow-lab.duckdns.org] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'jellyfin.snow-lab.duckdns.org'
  }
]
[2025-07-08T16:41:40.124Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-08T16:54:18.167Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-08T16:54:27.845Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-11T00:09:42.500Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-11T00:09:59.330Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
[2025-07-11T00:10:20.635Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}
